### PR TITLE
Correctly add task dependencies for uploaded files

### PR DESCRIPTION
**Pull request by SquidDev**
- Use `project.files(...)`/`FileCollection` to resolve artifacts, rather than rolling own our own function for this. This supports a wider range of Gradle's built-in types, such as `TaskProvider<T>`, making the plugin more friendly to use from Kotlin.

 - Add the appropriate `@Nested` and `@InputFiles` annotations so that Gradle scans the artifact `FileCollection` for task dependencies. This means that `publishCurseForge` automatically adds task dependencies for the files it depends on.

   Demo using the Forge test project and [the task-tree Gradle plugin](https://plugins.gradle.org/plugin/com.dorongold.task-tree):

   ```
   :publishCurseForge
   +--- :jar
   |    \--- :classes
   |         +--- :compileJava
   |         \--- :processResources
   +--- :javadocJar
   |    \--- :javadoc
   |         \--- :classes *
   \--- :sourcesJar
   ```

### CODE REVIEW

**Review by jaredlll08 — APPROVED** [review]

**Comment by SquidDev** [comment]
Thanks!

**Comment by pupnewfster** [comment]
@SquidDev question, I don't know if it is just an issue when I was rebasing #12 onto this or if it was just something missed in testing but for some reason as of this I get issues relating to the `UploadArtifact.curseFileId` not being annotated with `Input` or `Output`. Any ideas why? Annotating it as `Internal` seems to make it work but I am unsure if that is the correct solution and I am unsure why it was not run into while testing this PR. If it is just that some annotation was accidentally missed I can include it as a commit in my PR.

**Comment by SquidDev** [comment]
Oh, that's really odd, especially if it's not complaining about the other fields. I'm afraid I'm not quite sure why that's happening - I don't remember seeing anything when testing, but more than possible I missed something. Sorry!

It should be sufficient to mark it as `@Internal` here - ideally we'd able to mark it as an `@Output`, but I don't believe Gradle supports that :(.

**Comment by pupnewfster** [comment]
Yeah the fact it isn't complaining about the other fields is what confuses me though I am guessing it might be related to the getter at the bottom of `UploadArtifact` for that field? And sounds good I will just include a commit to my PR for marking it as internal as you are right it doesn't seem to like having it annotated at Output.

**Comment by SquidDev** [comment]
>  I am guessing it might be related to the getter at the bottom of `UploadArtifact` for that field? 

Ahh, good spot! Interesting that Gradle supports annotating the field rather than the getter method though.

> And sounds good I will just include a commit to my PR for marking it as internal 

Thank you :). Sorry about that!

**Pull request merged**
